name: flutter_helper
description: Collection of CLI commands to help with Flutter development.
version: 1.0.0
repository: https://github.com/akiortagem/flutter-helper

environment:
  sdk: ^3.0.0

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  args: any
  dart_style: any
  mustache_template: any

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
